# This file is generated by setup.py. DO NOT EDIT!

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

version = '1.6.0'
git_version = 'dd6085d35957da91929ca2bfa410772efda381d0'
